### PR TITLE
Crash fix

### PR DESCRIPTION
**Pull request by Code-Apprentice**
Unhandled exception when the league client is closed or reopened and you try to set runes.

Solved by adding a catch and attempting to connect to the riot api again, gracefully quitting if not detected.

Also cleaned unneeded build files

### CODE REVIEW

**Comment by Fumi24** [comment]
Will make a release soon with this fix included, thx!

**Comment by GameonRoki** [comment]
Hi sir can u please help me am struck in Unable to find hook point tmp/d20...?  how to fix this

**Comment by Fumi24** [comment]
@GameonRoki It would be good if you created an issue instead of using the pull request, as for the error im going to need a bit more information that that, Region / are you using windows etc?

**Comment by GameonRoki** [comment]
@Fumi24 Ues Sir windows 8. I have Updated the kali linux to 2018 version the New error is Unable to built an original apk

**Comment by GameonRoki** [comment]
Sir How to go through that...???

**Comment by Fumi24** [comment]
I dont support Linux in any shape or form.

**Comment by GameonRoki** [comment]
Its K sir I have Figued Out where is prblm... Thanx 4r ur reply☺️

**Comment by Code-Apprentice** [comment]
@GameonRoki I think you can build the source in Linux, WinForms is cross platform. It doesn't use any .NET CLR specific I think. But do it yourself 😄 

Also next time don't comment on a pull request, make a new issue please

**Comment by GameonRoki** [comment]
sure Sir😃

**Pull request merged**
